repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [ --fix ]
        files: ^lab_1/
      - id: ruff-format
        files: ^lab_1/

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        files: ^lab_1/
        stages: [pre-push]