default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff check
        entry: bash -c 'cd lab_1 && ruff check --fix .'
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: ruff-format
        name: ruff format
        entry: bash -c 'cd lab_1 && ruff format .'
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: pyright
        name: pyright
        entry: bash -c 'cd lab_1 && pyright'
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: pytest
        name: pytest
        entry: bash -c 'cd lab_1 && pytest'
        language: system
        pass_filenames: false
        stages: [pre-push]