CSV_FILENAME = '69.csv'
CSV_DELIMITER = ';'
COLUMN_EMAIL = 'email'
COLUMN_HTTP_STATUS = 'http_status_message'
COLUMN_INN = 'inn'
COLUMN_PASSPORT = 'passport'
COLUMN_IP_V4 = 'ip_v4'
COLUMN_LATITUDE = 'latitude'
COLUMN_HEX_COLOR = 'hex_color'
COLUMN_ISBN = 'isbn'
COLUMN_UUID = 'uuid'
COLUMN_TIME = 'time'
COLUMNS_TO_VALIDATE = [
    COLUMN_EMAIL,
    COLUMN_HTTP_STATUS,
    COLUMN_INN,
    COLUMN_PASSPORT,
    COLUMN_IP_V4,
    COLUMN_LATITUDE,
    COLUMN_HEX_COLOR,
    COLUMN_ISBN,
    COLUMN_UUID,
    COLUMN_TIME
]
RESULT_FILENAME = 'result.json'
