"""add_foreign_key

Revision ID: 2a3755dd81de
Revises: c6ccb98e1d04
Create Date: 2024-08-31 18:10:50.957838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a3755dd81de"
down_revision: Union[str, None] = "c6ccb98e1d04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "item", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "item", type_="foreignkey")
    op.drop_column("item", "user_id")
    # ### end Alembic commands ###
