# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aud.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 620)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ope_folder = QtWidgets.QPushButton(self.centralwidget)
        self.ope_folder.setGeometry(QtCore.QRect(225, 0, 31, 31))
        self.ope_folder.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Folder_open_alt_font_awesome.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ope_folder.setIcon(icon)
        self.ope_folder.setIconSize(QtCore.QSize(30, 30))
        self.ope_folder.setObjectName("ope_folder")
        self.pause = QtWidgets.QPushButton(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(225, 390, 30, 30))
        self.pause.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pause_-_The_Noun_Project.svg.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pause.setIcon(icon1)
        self.pause.setIconSize(QtCore.QSize(36, 36))
        self.pause.setObjectName("pause")
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(130, 390, 30, 30))
        self.left.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Iconoir_arrow-left-circled.svg — копия.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap("Pause_-_The_Noun_Project.svg.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.left.setIcon(icon2)
        self.left.setIconSize(QtCore.QSize(36, 36))
        self.left.setObjectName("left")
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(320, 390, 30, 30))
        self.right.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Iconoir_arrow-left-circled.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("Pause_-_The_Noun_Project.svg.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.right.setIcon(icon3)
        self.right.setIconSize(QtCore.QSize(36, 36))
        self.right.setObjectName("right")
        self.time_line = QtWidgets.QSlider(self.centralwidget)
        self.time_line.setGeometry(QtCore.QRect(130, 320, 221, 21))
        self.time_line.setOrientation(QtCore.Qt.Horizontal)
        self.time_line.setObjectName("time_line")
        self.volume = QtWidgets.QSlider(self.centralwidget)
        self.volume.setGeometry(QtCore.QRect(430, 110, 22, 160))
        self.volume.setOrientation(QtCore.Qt.Vertical)
        self.volume.setObjectName("volume")
        self.loop = QtWidgets.QPushButton(self.centralwidget)
        self.loop.setGeometry(QtCore.QRect(225, 460, 30, 30))
        self.loop.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("povtor_gdyrn6c8sc5s.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap("Pause_-_The_Noun_Project.svg.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.loop.setIcon(icon4)
        self.loop.setIconSize(QtCore.QSize(36, 36))
        self.loop.setObjectName("loop")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 220, 161, 81))
        self.label.setStyleSheet("font: 48pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
