repos:
  - repo: https://github.com/ProFootik/prog-instruments-labs.git
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/ProFootik/prog-instruments-labs.git
    rev: v1.1.360
    hooks:
      - id: pyright