name: Result check for lab 3

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - 'main'
    paths:
      - 'lab_3/**'
permissions:
  contents: read

jobs:
  check-result:
    runs-on: ubuntu-latest

    steps:
      - name: Get result.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          gh api \
            "repos/${REPOSITORY}/contents/lab_3/result.json?ref=${SHA}" \
            --header "Accept: application/vnd.github.raw+json" \
            > result.json

      - name: Read result
        id: your_results
        run: |
          variant=$(jq -r '.variant' result.json)
          checksum=$(jq -r '.checksum' result.json)

          echo "variant=$variant" >> "$GITHUB_OUTPUT"
          echo "checksum=$checksum" >> "$GITHUB_OUTPUT"

      - name: Displaying your results
        run: |
          echo "your variant: ${{ steps.your_results.outputs.variant }}"
          echo "your checksum: ${{ steps.your_results.outputs.checksum }}"

      - name: checking your results 
        run: |
          array=${{ secrets.CHECKSUMS }}
          sum=${{steps.your_results.outputs.checksum}}
          vnt=${{steps.your_results.outputs.variant}}
          cnt=0
          for item in ${array[*]}
          do
          cnt=$((cnt+1))
          if [[ $item == $sum ]]; then
              if [[ $cnt == $vnt ]]; then
                echo "Congratulations, your results are correct"
                exit 0
              fi
          fi
          done
          echo "Your results are not correct. Correct checksum for your variant is ${array[$vnt-1]}"
          exit 1
