name: Unit testing for lab 5

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - 'main'
    paths:
      - 'lab_5/**'
      
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout your fork
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpulse-mainloop-glib0 libqt5multimedia5 libqt5multimedia5-plugins libqt5multimediagsttools qt5-default xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest coverage
    
    - name: Set env path
      run: |
        export PYTHONPATH=.:$PYTHONPATH:lab_5/
             
    - name: Run tests
      run: |
        xvfb-run -s "-screen 0 1024x768x24" coverage run -m pytest

    - name: Calculate code coverage
      run: |
        coverage report
